name: impulse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_settings: ^4.3.1
  barcode_widget: ^2.0.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  desktop_drop: ^0.4.3
  equatable: ^2.0.5
  file_picker: ^5.3.4
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.3.6
  flutter_sharing_intent: ^1.1.0
  flutter_svg: ^2.0.7
  go_router: ^8.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  impulse_utils:
    git:
      url: https://github.com/kannel-outis/impulse_utils.git
  mime: ^1.0.4
  open_file: ^3.3.2
  path_drawing: ^1.0.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  qr_code_scanner: ^1.0.1
  riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  vibration: ^1.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/josefin/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/josefin/josefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/josefin/josefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/josefin/josefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/josefin/josefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/josefin/josefinSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/josefin/josefinSans-SemiBold.ttf
          weight: 700

    - family: icomoon
      fonts:
        - asset: assets/fonts/icons/icomoon.ttf

    - family: transfer
      fonts:
        - asset: assets/fonts/icons/transfer_icons.ttf

    - family: transfer2
      fonts:
        - asset: assets/fonts/icons/transfer_2.ttf

flutter_native_splash:
  color: "#E9F2E3"
  image: assets/logo/logo-dark.png
  branding: assets/logo/brand-dark.png
  color_dark: "#211C1D"
  image_dark: assets/logo/logo.png
  branding_dark: assets/logo/brand.png

  android_12:
    image: assets/logo/logo-dark.png
    icon_background_color: "#E9F2E3"
    image_dark: assets/logo/logo.png
    icon_background_color_dark: "#211C1D"

msix_config:
  display_name: Impulse
  publisher_display_name: T.K apps
  identity_name: impulse.app
  msix_version: 1.0.0.0
  logo_path: .\windows\runner\resources\app_icon.ico
