name: Release impulse on windows and android


concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true



on:
    pull_request:
        types:
            [closed]
        branches:
            - main
        paths-ignore:
            - '**.md'
            - 'doc/**'
            - '.git/'
            - '.vscode/'


jobs:
    build_and_upload_android_artifacts:
        name: Build and Upload android artifacts
        uses: ./.github/workflows/build-android.yml
        secrets: inherit

    build_and_upload_windows_artifacts:
        name: Build and upload windows artifacts
        uses: ./.github/workflows/build-windows.yml

    download_and_release_artifacts:
        if: github.event.pull_request.merged == true
        needs: [build_and_upload_android_artifacts, build_and_upload_windows_artifacts]
        name: Download and create release for the artifacts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get version from pubspec.yaml
              id: impulse_version
              run: |
                VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' pubspec.yaml)
                echo "version=$VERSION" >> $GITHUB_OUTPUT


            - name: create build directory
              run: |
                mkdir build
                cd build
                mkdir windows

            - name: download app-armeabi-v7a-release apk
              uses: actions/download-artifact@v3
              with:
                name: app-armeabi-v7a-release
                path: build

            - name: download app-arm64-v8a-release apk
              uses: actions/download-artifact@v3
              with:
                name: app-arm64-v8a-release
                path: build

            - name: download app-x86_64-release apk
              uses: actions/download-artifact@v3
              with:
                name: app-x86_64-release
                path: build


            - name: download impulse windows msix file
              uses: actions/download-artifact@v3
              with:
                name: impulse-windows
                path: build

            - name: download impulse-windows zip
              uses: actions/download-artifact@v3
              with:
                name: impulse-windows-zip
                path: build/windows


            - name: zip windows exe files
              run: |
                zip -r build/windows-v${{ steps.impulse_version.outputs.version }}.zip build/windows/* -x 'build/windows/*.msix'


            
            - name: Display structure of downloaded files
              run: ls -R
              working-directory: build/
            

            - name: Rename artifacts
              run: |
                mv build/app-armeabi-v7a-release.apk build/impulse-v${{ steps.impulse_version.outputs.version }}-armeabi-v7a.apk
                mv build/app-arm64-v8a-release.apk build/impulse-v${{ steps.impulse_version.outputs.version }}-arm64-v8a.apk
                mv build/app-x86_64-release.apk build/impulse-v${{ steps.impulse_version.outputs.version }}-x86_64.apk
                mv build/impulse.msix build/impulse-v${{ steps.impulse_version.outputs.version }}.msix



            - name: create Release
              uses: ncipollo/release-action@v1.13.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                tag: v${{ steps.impulse_version.outputs.version }}
                artifacts: "build/impulse-v${{ steps.impulse_version.outputs.version }}-armeabi-v7a.apk, build/impulse-v${{ steps.impulse_version.outputs.version }}-arm64-v8a.apk, build/impulse-v${{ steps.impulse_version.outputs.version }}-x86_64.apk, build/github_actions_test.msix, build/windows-v${{ steps.impulse_version.outputs.version }}.zip"
                # allowUpdates: true
                generateReleaseNotes: true